apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-file
data:
  mosquitto.conf: |
    log_dest stdout
    log_type all
    log_timestamp true
    listener 9001
    
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-file
type: Opaque
data:
  secret.file: |
    SGlpIEFhcnlhICEhIEl0J3MgeW91ciBzZWNyZXQgZmlsZQ==
